### ISSUE TITLE
复现需要多少epoch？设置哪些参数

### ISSUE THREAD

**Issue by Tong-Hao741** [dulucas/siMLPe#13]
请问需要多少epoch能够复现论文结果呢？，需要在哪里设置epoch？因为目前实验效果达不到论文，请告诉我准确的参数吧，十分感谢！
How many epochs are needed to reproduce the results of the paper?, Where do I need to set an epoch? Because the current experimental results cannot meet the requirements of the paper, please tell me the accurate parameters. Thank you very much!

**Comment by GUO-W** [comment]
Hello, please see our latest update. The previous checkpoint was not correctly uploaded and has been deprecated. we uploaded the correct checkpoints at 35000 iters and 40000 iters. We use exact the same scripts as provided in this repo. Furthermore, we uploaded the [log](https://github.com/dulucas/siMLPe/blob/main/exps/baseline_h36m/log/log_2024_04_14_06_35_34.log) and [tensorboard checkpoints](https://github.com/dulucas/siMLPe/tree/main/exps/baseline_h36m/runs) of the training so you could have a better overview of the training details etc.

The results of [35000 iters model](https://github.com/dulucas/siMLPe/blob/main/checkpoints/h36m_model_35000.pth):
[9.6, 21.7, 46.3, 57.2, 75.8, 89.7, 101.1, 108.7]
The results of [40000 iters model](https://github.com/dulucas/siMLPe/blob/main/checkpoints/h36m_model_40000.pth):
[9.6, 21.7, 46.4, 57.4, 76.1, 90.1, 101.6, 109.2]

Due to the lack of GPUs, we trained our model on a Mac air with M2 chip. It took us about 4h40 to finish the training. It would  be much more faster if you train it on a GPU with multi-processing dataloader.

**Comment by Tong-Hao741** [comment]
感谢你的回复，我会尝试继续测试，再次感谢：)
Thank you for your reply. I will try to continue testing. Thank you again: : )

**Comment by Tong-Hao741** [comment]
在阅读代码时我发现论文使用了22个人体关节点，请问为什么不是原数据的25个呢？
When reading the code, I found that the paper used 22 human joint points. May I ask why it is not the original data of 25?

**Comment by dulucas** [comment]
To keep align with previous works like LTD, Hisrep etc for a fair comparison

**Comment by Tong-Hao741** [comment]
thank u~

**Comment by Tong-Hao741** [comment]
作者你好，我有一个小疑问，就是对时间维度经过DCT变换后数据还含有时间信息吗？因为我看到论文代码中有temporal_fc模块

Hello author, I have a small question, is there still time information in the data after DCT transformation of the time dimension? Because I saw the temporal_fc module in the paper code

**Comment by dulucas** [comment]
Yes.
